# Generated by Django 3.2.12 on 2022-09-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('m', 'M'), ('f', 'Ж')], default='m', max_length=15),
        ),
    ]
