# Generated by Django 3.2.12 on 2022-09-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='choi',
            field=models.BooleanField(default=False, verbose_name='Подписка'),
        ),
    ]
