# Generated by Django 3.2.12 on 2022-09-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_choi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='choi',
            field=models.BooleanField(blank=True, default=True, verbose_name='Подписка'),
        ),
    ]
