# Generated by Django 3.2.12 on 2022-09-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('text', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='lemon/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
